### ISSUE TITLE
Hello👋, from HNG-11 slack intern😎

### ISSUE THREAD

**Issue by Lucky-tech10** [CodeDeveloper19/my-portfolio-site#1]
What’s up man, want to connect with you and get more knowledge in web dev from you. If you can give me insights on some area. 
I see you are an intern in HNG-11.
I was there to but couldn’t pass stage 5 tho I got to stage 5 via premium lol.
Can we connect please?
Also are you still in the HNG slack?

pls respond…🙏🏾

**Comment by CodeDeveloper19** [comment]
Sure no problem
________________________________
From: Ezihe, Goodluck Chidera ***@***.***>
Sent: Monday, July 29, 2024 10:37 AM
To: CodeDeveloper19/my-portfolio-site ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CodeDeveloper19/my-portfolio-site] Hello👋, from HNG-11 slack intern😎 (Issue #1)


What’s up man, want to connect with you and get more knowledge in web dev from you. If you can give me insights on some area.
I see you are an intern in HNG-11.
I was there to but couldn’t pass stage 5 tho I got to stage 5 via premium lol.
Can we connect please?
Also are you still in the HNG slack?

pls respond…🙏🏾

**Comment by Lucky-tech10** [comment]
Thanks.
Can I get your WhatsApp number or something I can message you privately
with?

**Comment by CodeDeveloper19** [comment]
08182768105
________________________________
